name: flutter_github_cicd
description: ""
publish_to: 'none'
version: 1.1.6+6


environment:
  sdk: ^3.7.2



dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  flutter_launcher_icons: ^0.14.3
  platform: ^3.1.6
  get: ^4.7.2
  marquee: ^2.3.0
  device_info_plus:
  connectivity_plus:
  fluttertoast: ^8.2.12
  dio: ^5.8.0+1
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0
  file_picker: ^10.1.2
  intl: ^0.20.2
  flutter_easyloading: ^3.0.5
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  adaptive_theme: ^3.7.0
  delayed_display: ^2.0.0
  open_file: ^3.5.10
  syncfusion_flutter_charts: ^29.1.40
  syncfusion_flutter_pdfviewer: ^29.1.40
  flutter_inappwebview: ^6.1.5
  stepper_a: ^1.3.1
  sizer: ^3.0.5
  flutter_chat_types: ^3.6.2
  image_picker: ^1.1.2
  badges: ^3.1.2
  pinput: ^5.0.1
  flutter_chat_ui: ^1.6.15
  cached_network_image: ^3.4.1
  mobile_scanner: ^6.0.10
  carousel_slider: ^5.0.0



  uuid: any
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo.jpg"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
