// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeX1pQTh-RRV7LojK6VjFfZs9j29UtPFs',
    appId: '1:78791143447:web:bb24c8969e5dd10c9d2c52',
    messagingSenderId: '78791143447',
    projectId: 'flutter-github-cicd',
    authDomain: 'flutter-github-cicd.firebaseapp.com',
    storageBucket: 'flutter-github-cicd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANT2OU7RYhukEyW43UIhQVUgP4oOp3oIw',
    appId: '1:78791143447:android:d09e625f5e6145959d2c52',
    messagingSenderId: '78791143447',
    projectId: 'flutter-github-cicd',
    storageBucket: 'flutter-github-cicd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF_fvqGt_hHqMXcJHNq68e4Kr8hA_ddKs',
    appId: '1:78791143447:ios:9031d0c69b0633fb9d2c52',
    messagingSenderId: '78791143447',
    projectId: 'flutter-github-cicd',
    storageBucket: 'flutter-github-cicd.firebasestorage.app',
    iosBundleId: 'com.samir.flutterGithubCicd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF_fvqGt_hHqMXcJHNq68e4Kr8hA_ddKs',
    appId: '1:78791143447:ios:9031d0c69b0633fb9d2c52',
    messagingSenderId: '78791143447',
    projectId: 'flutter-github-cicd',
    storageBucket: 'flutter-github-cicd.firebasestorage.app',
    iosBundleId: 'com.samir.flutterGithubCicd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeX1pQTh-RRV7LojK6VjFfZs9j29UtPFs',
    appId: '1:78791143447:web:69d2770f2df8c3f69d2c52',
    messagingSenderId: '78791143447',
    projectId: 'flutter-github-cicd',
    authDomain: 'flutter-github-cicd.firebaseapp.com',
    storageBucket: 'flutter-github-cicd.firebasestorage.app',
  );
}
