name: Flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  flutter_job:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

      # ✅ Build Android APK
      - name: Build Android APK
        run: flutter build apk --release

      # ✅ Upload APK to Firebase App Distribution
      - name: Upload APK to Firebase App Distribution
        if: success()
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID_ANDROID }} \
            --token ${{ secrets.FIREBASE_CLI_TOKEN }} \
            --groups "all_testers"

      # ✅ Build iOS IPA (Add ExportOptions.plist with signing configs)
      - name: Build iOS IPA
        run: flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

      # ✅ Upload IPA to Firebase App Distribution
      - name: Upload IPA to Firebase App Distribution
        if: success()
        run: |
          firebase appdistribution:distribute build/ios/ipa/Runner.ipa \
            --app ${{ secrets.FIREBASE_APP_ID_IOS }} \
            --token ${{ secrets.FIREBASE_CLI_TOKEN }} \
            --groups "all_testers"
